az_location = "East US 2"
az_prefix = "example"
az_vnet_address_space = "10.0.0.0/16"
az_subnet_address_prefix = "10.0.1.0/24"
az_volume_path = "my-unique-file-path"
az_capacity_pool_size = 4
az_vnet_creation_bool = false
az_subnet_creation_bool = false
az_subnet_id_for_anf_vol = "subnet-id-here"
az_netapp_pool_service_level = "Premium"
az_netapp_vol_service_level = "Premium"
az_netapp_vol_protocol = "NFSv4.1"
az_netapp_vol_storage_quota = 100
az_snapshot_id = "snapshot id here"
